# Configuration for Calm Style using Built-in Academic Theme
# Uses the academic-minimal theme with clean, simple design

version: '1.0'
name: calm-builtin-config
description: Calm style with built-in academic-minimal theme

# Output configuration
output:
  formats: ["html"]  # Generate HTML slides with built-in theme
  directory: "outputcb"

# Slides configuration with built-in theme
slides:
  theme: "academic-minimal"
  template: null
  max_content_length: 1000
  auto_split: true
  transition: "none"
  controls: true
  progress: false
  center: true
  touch: true
  fragments: false
  navigation_mode: default
