# Configuration for Fancy Style using Standard RevealJS Theme
# Uses the 'moon' theme with dynamic animations and effects

version: '1.0'
name: config
description: Fancy style with standard RevealJS theme

# Output configuration
output:
  formats: ["revealjs"]  # Generate HTML slides with standard RevealJS theme
  directory: "output"

# Slides configuration with standard RevealJS theme
slides:
  theme: "night"  
  template: null
  max_content_length: 1000
  auto_split: true
  transition: "slide"  # Standard slide transition
  controls: true
  progress: true
  center: true
  touch: true
  fragments: true  # Enable fancy fragment animations
  navigation_mode: default

# Notes configuration: generate HTML notes as requested
notes:
  formats: ["html"]
