# Configuration for Calm Style using Standard RevealJS Theme
# Uses the 'white' theme with minimal animations and clean design

version: '1.0'
name: calm-revealjs-config
description: Calm style with standard RevealJS white theme

# Output configuration
output:
  formats: ["html"]  # Generate HTML slides with standard RevealJS theme
  directory: "outputcr"

# Slides configuration with standard RevealJS theme
slides:
  theme: "white"  # Clean, minimal white RevealJS theme
  template: null
  max_content_length: 1000
  auto_split: true
  transition: "none"  # No transitions for calm presentation
  controls: true
  progress: false  # Minimal UI for calm style
  center: true
  touch: true
  fragments: false  # No fragment animations for calm style
  navigation_mode: default
