# Configuration for Fancy Style using Built-in Academic Theme
# Uses the academic-elegant theme with sophisticated design

version: '1.0'
name: fancy-builtin-config
description: Fancy style with built-in academic-elegant theme

# Output configuration
output:
  formats: ["html"]
  directory: "outputfb"

# Slides configuration with built-in theme
slides:
  theme: "academic-elegant"
  template: null
  max_content_length: 1000
  auto_split: true
  transition: "slide"
  controls: true
  progress: true
  center: true
  touch: true
  fragments: true
  navigation_mode: default
  help: true
  show_notes: false
