# Configuration for White Theme with Enhanced Features

version: '1.0'
name: config
description: White theme with enhanced code styling and UI features

# Output configuration
output:
  formats: ["revealjs"]
  directory: "output"
  overwrite: true

# Slides configuration
slides:
  theme: "academic-modern"
  transition: "slide"
  controls: true
  progress: true
  center: true
  touch: true
  fragments: true
  preview_links: true
  help: true
  show_notes: false
  navigation_mode: default
  css: 
    - "fancy-sans-overrides.css"
  js:
    - "reveal-slide-ui.js"

# Processing settings - enable good styling features
processing:
  intelligent_splitting: true
  syntax_highlighting: true
  math_renderer: "mathjax"
  content_validation: true
  image_optimization: true

# Notes configuration
notes:
  formats: ["html"]
  style: "academic"
  include_toc: true

# Variables for templating
variables:
  author: "Vincenzo Ciancia"
  institution: "University of Pisa"
