# Configuration for White Theme with Enhanced Features

version: '1.0'
name: config
description: White theme with enhanced code styling and UI features

# Output configuration
output:
  formats: ["revealjs"]
  directory: "output"
  overwrite: true

# Slides configuration
slides:
  theme: "styles/unipi-lecture01-fancy-sans.scss"
  transition: "slide"
  controls: true
  progress: true
  center: true
  touch: true
  fragments: true
  preview_links: true
  help: true
  show_notes: false
  navigation_mode: default
  viewport_width: 1200
  viewport_height: 1080

# Processing settings - enable good styling features
processing:
  intelligent_splitting: false
  syntax_highlighting: true
  math_renderer: "mathjax"
  content_validation: false
  image_optimization: true

# Notes configuration
notes:
  formats: ["html"]
  style: "academic"
  include_toc: true

# Variables for templating
variables:
  author: "Vincenzo Ciancia"
  institution: "Istituto di Scienza e Tecnologie dell'Informazione, Consiglio Nazionale delle Ricerche (ISTI-CNR)"
