# Configuration for Fancy Style using Standard RevealJS Theme
# Uses the 'moon' theme with dynamic animations and effects

version: '1.0'
name: fancy-revealjs-config
description: Fancy style with standard RevealJS moon theme

# Output configuration
output:
  formats: ["html"]  # Generate HTML slides with standard RevealJS theme
  directory: "outputfr"

# Slides configuration with standard RevealJS theme
slides:
  theme: "moon"  # Dark, elegant RevealJS theme with fancy styling
  template: null
  max_content_length: 1000
  auto_split: true
  transition: "slide"  # Standard slide transition
  controls: true
  progress: true
  center: true
  touch: true
  fragments: true  # Enable fancy fragment animations
  navigation_mode: default
