version: '1.0'
name: standard-config
description: Standard configuration for typical usage
output:
  formats:
  - html
  - pdf
  directory: ./output
  preserve_structure: true
  overwrite: true
  naming_pattern: '{stem}_{type}.{ext}'
slides:
  theme: academic-elegant
  template: null
  max_content_length: 1000
  auto_split: true
  transition: slide
  controls: true
  progress: true
  center: true
  touch: true
  loop: false
  rtl: false
  navigation_mode: default
  shuffle: false
  fragments: true
  embedded: false
  help: true
  show_notes: false
  auto_slide: 0
  auto_slide_stoppable: true
  mouse_wheel: false
  hide_address_bar: true
  preview_links: false
  viewport_width: 1024
  viewport_height: 768
  viewport_scale: 1.0
notes:
  style: solarized
  template: null
  include_toc: true
  page_numbers: true
  line_numbers: false
  margin_notes: false
  bibliography: true
  cross_references: true
  figure_captions: true
  table_captions: true
  equation_numbers: true
  header_includes: []
  geometry: margin=1in
  font_size: 11pt
  font_family: default
  line_spacing: single
processing:
  intelligent_splitting: true
  preserve_formatting: true
  syntax_highlighting: true
  math_renderer: mathjax
  latex_packages: []
  custom_commands: {}
  image_optimization: true
  link_validation: false
  content_validation: true
batch:
  pattern: '*.md'
  recursive: false
  parallel: true
  max_workers: 4
  progress_reporting: true
  error_handling: continue
  file_filters: []
  exclude_patterns: []
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null
  max_size: 10MB
  backup_count: 5
  console: true
  colors: true
variables:
  author: Prof. Vincenzo Ciancia
  institute: University of Pisa
custom: {}
